sudo: requried
services:
  - docker

before_install:
  - docker build -t ermannb/react-test -f ./client/Dockerfile.dev ./client

script:
  - docker run -e CI=true ermannb/react-test npm test

after_success:
  - docker build -t ermannb/multi-client ./client
  - docker build -t ermannb/multi-server ./server
  - docker build -t ermannb/multi-nginx ./nginx
  - docker build -t ermannb/multi-worker ./worker
