sudo: required
services:
  - docker

before_install:
  - docker build -t ermannb/react-test -f ./client/Dockerfile.dev ./client

script:
  - docker run -e CI=true ermannb/react-test npm test

after_success:
  - docker build -t ermannb/multi-client ./client
  - docker build -t ermannb/multi-server ./server
  - docker build -t ermannb/multi-nginx ./nginx
  - docker build -t ermannb/multi-worker ./worker
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
  - docker push ermannb/multi-client
  - docker push ermannb/multi-server
  - docker push ermannb/multi-nginx 
  - docker push ermannb/multi-worker

deploy:
  edge: true
  provider: elasticbeanstalk
  region: "us-east-1"
  app: "docker-complex"
  env: "DockerComplex-env"
  bucket_name: "elasticbeanstalk-us-east-1-018991611705"
  bucket_path: "docker-complex"
  on:
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: "$AWS_SECRET_KEY"
